# 1.
# a = "hello world! python is fun"
# print(a.count("o"))

# 2.
# a = "python is easy and fun"
# a = a.split()
# print(a)

# 3.
# a = ['cat','dog','bird','fish']
# b = ['rabbit','turtle']
# a.extend(b)
# del a[1]
# print(a)

# 4.
# a = []
# b = [1,2,3,4,5,6,7,8]
# for i in b:
# if i%3==0:
# a.append(i)
# print(a)

# 5.
# a = {'苹果': 5, '香蕉': 3, '橙子': 4}
# a['香蕉'] = 6
# a['葡萄'] = 7
# print(a)

# 6.
# a = {}
# s1 = {'a', 'b', 'c', 'd'}
# s2 = {'c', 'd', 'e', 'f'}
# b = s1 & s2
# c = s1 | s2
# a['交集']= b
# a['并集']= c
# print(a)
